"use client";

import { useMemo, useState } from "react";
import { Button, Metric, PageHeader, Panel, Tag } from "./NgoUI";
import styles from "./NgoDashboard.module.css";

const missions=[
  {id:"MSN-2025-00418",status:"IN-PROGRESS · 78% CLEARED",tone:"red",severity:"HIGH SEVERITY",title:"Ward 84 • Yamuna Ghat Plastic Interception & Storm Drain Desilting",place:"GPS 28.6658° N, 77.2341° E (Citizen Geotag Confirmed by Meera K. + 14 co-signers)",time:"3h 14m",started:"Started Today 07:30 AM",image:"/citizen/mission-yamuna.png",label:"AI Scan: 14.8 MT est.",crew:"12 Safai Sathis + Lead",machine:"1 JCB + 1 Tipper Truck",grant:"₹4,80,000",progress:78},
  {id:"MSN-2025-00412",status:"CERTIFIED CLOSED & ESCROW SETTLED",tone:"green",severity:"ROUTINE RECLAMATION",title:"Ward 54 • Seelampur Flyover Pier #12 Underpass Rubble & Market Waste",place:"Dual Sign-off: Ward Junior Engineer A. Sharma & NGO Lead Inspector V. Nair",time:"2h 18m",started:"1h 42m ahead of SLA",image:"/citizen/mission-kashmere.png",label:"Before / after verified",crew:"8 Safai Sathis",machine:"1 Suction Jetter",grant:"₹2,50,000",progress:100},
  {id:"MSN-2025-00398",status:"CLOSED · BIO-METHANATION CONFIRMED",tone:"blue",severity:"WARD 108",title:"Ward 108 • Ghazipur Wholesale Mandi Bio-Waste Segregation & Perimeter Clearing",place:"8.6 MT organic compostable waste diverted directly to biomethanizer",time:"4h 05m",started:"06:00 AM → 10:05 AM",image:"/citizen/mission-mori-gate.png",label:"8.6 MT diverted",crew:"10 Safai Sathis",machine:"1 Compactor",grant:"₹3,20,000",progress:100},
  {id:"MSN-2025-00431",status:"EN ROUTE · ETA: 18M",tone:"green",severity:"FIELD DEPLOYMENT",title:"Ward 84 • Old Delhi Railway Station Culvert Desilting",place:"Suction Jetter #SJ-02 mobilized · Operator: Satnam Singh (ETA 18 min)",time:"2h 30m",started:"Deployment scheduled 11:45 AM",image:"/citizen/report-drain.png",label:"Crew en route",crew:"6 Safai Sathis",machine:"Suction Jetter #02",grant:"₹1,80,000",progress:22},
];
const tabs=["All Undertaken (64)","Active On-Site (12)","Completed & Closed (48)","Dual Evidence Verified (24)","Awaiting Weighbridge Slip"];

export default function NgoDashboard(){
  const [tab,setTab]=useState(tabs[0]);const [query,setQuery]=useState("");const [notice,setNotice]=useState("");
  const visible=useMemo(()=>missions.filter(item=>(tab===tabs[1]?item.progress<100:tab===tabs[2]?item.progress===100:true)&&`${item.title} ${item.id} ${item.place}`.toLowerCase().includes(query.toLowerCase())),[tab,query]);
  return <>
    <PageHeader eyebrow="Undertaken Missions Log" title="All Undertaken Missions & Field Operations" description="Municipal registry of NGO-led cleanups, mechanized desilting, volunteer deployments, turnaround durations, and corporate CSR escrow releases across NCT wards 54, 84, and 108." actions={<><select aria-label="Date range" className={styles.date}><option>Date Range: Q1 2025 (Jan - Mar)</option><option>Q4 2024 (Oct - Dec)</option></select><Button variant="plain" onClick={()=>setNotice("Telemetry export prepared (mock)")}>↓ Export Telemetry (CSV/PDF)</Button><Button onClick={()=>setNotice("Rapid sweep deployment started (mock)")}>⊕ Deploy Rapid Sweep</Button></>}/>
    <div className={styles.metrics}><Metric label="Total missions undertaken" value="64" detail="48 Closed · 12 Active · 4 Mobilizing"/><Metric label="Avg turnaround duration" value="3h 42m" detail="48m faster than SLA target" tone="mint" icon="◷"/><Metric label="Cumulative diverted waste" value="342.8 MT" detail="Weighbridge Certified Load" tone="blue" icon="♧"/><Metric label="CSR escrow settlements" value="₹28.40L" detail="₹24.80L Verified & Disbursed" tone="green" icon="▣"/></div>
    <Panel className={styles.controls}><div className={styles.tabs}>{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?styles.selected:""}>{item}</button>)}</div><div className={styles.search}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="⌕  Search by Mission ID, ward, landmark, team lead…"/><select aria-label="Assigned ward"><option>All Assigned Wards (54, 84, 108)</option><option>Ward 54 · Seelampur</option><option>Ward 84 · Kashmere Gate</option><option>Ward 108 · Ghazipur Mandi</option></select><select aria-label="Duration"><option>Any Duration</option><option>Within SLA</option><option>Over SLA</option></select></div></Panel>
    {notice&&<div className={styles.notice} role="status">✓ {notice}<button onClick={()=>setNotice("")} aria-label="Dismiss">×</button></div>}
    <div className={styles.layout}><div className={styles.missionList}>{visible.length===0?<Panel><p className={styles.empty}>No missions match this search.</p></Panel>:visible.map(mission=><Panel key={mission.id} className={styles.mission}><div className={`${styles.edge} ${styles[mission.tone]}`}/><div className={styles.missionBody}><div className={styles.labels}><Tag tone={mission.tone as "red"|"green"|"blue"}>{mission.status}</Tag><Tag tone={mission.tone==="red"?"red":"gray"}>{mission.severity}</Tag><small>ID: #{mission.id}</small></div><h2>{mission.title}</h2><p className={styles.place}>⌖ {mission.place}</p><div className={styles.duration}><small>ELAPSED DURATION</small><b>{mission.time}</b><span>{mission.started}</span></div>{mission.progress<100?<><div className={styles.sla}><div><span>◷ SLA Allowance: 5h 00m Total</span><b>{Math.max(0,5*60-194)}m remaining within SLA window</b></div><div className={styles.bar}><span style={{width:`${mission.progress}%`}}/></div><small>Dispatched: 07:30 AM <b>Target Cutoff: 12:30 PM (Est. Finish: 11:30 AM)</b></small></div><div className={styles.operation}><img src={mission.image} alt="Sanitation mission field evidence"/><div><span><small>CREW DEPLOYMENT</small><b>{mission.crew}</b><small>Lead: R. Paswan (Level 3)</small></span><span><small>HEAVY MACHINERY</small><b>{mission.machine}</b><small>Vehicle #DL-1M-4920</small></span><span className={styles.grant}><small>CSR ESCROW ALLOCATION</small><b>{mission.grant}</b><small>80% Escrow Locked</small></span></div></div><div className={styles.actions}><Button onClick={()=>setNotice(`Evidence upload opened for ${mission.id} (mock)`)}>♧ Upload Progress Evidence</Button><Button variant="soft" onClick={()=>setNotice(`Mission ${mission.id} location opened (mock)`)}>⌖</Button><Button variant="soft" onClick={()=>setNotice("Volunteer roster opened (mock)")}>♧ 14 Volunteers</Button></div></>:<><div className={styles.beforeAfter}><img src={mission.image} alt="Verified cleanup evidence"/><div><b>{mission.label}</b><small>AI Delta: 98.4% Clean · Weighbridge Verified</small></div></div><div className={styles.completedData}><span><small>Turnaround Timeline</small><b>{mission.started}</b></span><span><small>Citizen Re-verification</small><b>28 of 28 Positive</b></span><span><small>CSR Fund Settled</small><b>{mission.grant} Released</b></span><span><small>Recurrence Guard</small><b>0 Re-dump in 14 Days</b></span></div><div className={styles.actions}><Button variant="soft" onClick={()=>setNotice("Settlement ledger opened (mock)")}>View Settlement Ledger</Button><Button onClick={()=>setNotice("CSR audit certificate downloaded (mock)")}>♧ CSR Audit Certificate</Button></div></>}</div></Panel>)}</div>
      <aside className={styles.aside}><Panel><div className={styles.asideHead}><h2>SLA Performance by Ward</h2><Tag tone="green">01 Benchmark</Tag></div><p className={styles.asideIntro}>Turnaround compliance evaluated against NCT Municipal 4-hour remediation baseline.</p>{[["Ward 84 (Kashmere Gate)","99.1%","2h 26m","28 Missions Cleared"],["Ward 54 (Seelampur)","97.8%","3h 14m","22 Missions Cleared"],["Ward 108 (Ghazipur Mandi)","96.4%","3h 48m","14 Missions Cleared"]].map(row=><div className={styles.ward} key={row[0]}><div><b>{row[0]}</b><strong>{row[1]} Compliance</strong></div><div className={styles.bar}><span style={{width:row[1]}}/></div><small>Avg Duration: {row[2]} <i>{row[3]}</i></small></div>)}</Panel><Panel><h2 className={styles.asideTitle}>CSR Escrow Allocation</h2><div className={styles.donut}><span><b>87.3%</b><small>SETTLED</small></span></div>{[["Tata Clean Urban Mission","₹11.20 L"],["DLF Urban Reclaim Escrow","₹8.40 L"],["ITC Sunehra Kal & Hero","₹8.80 L"]].map(([name,value])=><p className={styles.sponsor} key={name}><b>●</b>{name}<strong>{value}</strong></p>)}</Panel><Panel><div className={styles.asideHead}><h2>Volunteer Standby</h2><Tag tone="green">34 Nearby</Tag></div><p className={styles.asideIntro}>Registered Safai Sathis within a 2.5 km radius of Ward 84 & 54 nodes ready for rapid deployment.</p><div className={styles.avatars}><i>AK</i><i>MS</i><i>RP</i><i>VJ</i><i>+30</i></div><Button variant="soft" onClick={()=>setNotice("Flash mobilization message queued (mock)")}>♧ Broadcast Flash Mobilization SMS</Button></Panel><Panel><div className={styles.asideHead}><h2>Machinery & Fleet Status</h2><Tag tone="green">100% Operational</Tag></div>{[["♧","JCB Excavator #01","Active On-Site"],["⌁","Suction Jetter #02","En Route"],["▰","10-Ton Tipper #04","Payload Transit"]].map(item=><div className={styles.fleet} key={item[1]}><b>{item[0]}</b><span><strong>{item[1]}</strong><small>{item[2]}</small></span></div>)}</Panel></aside></div>
  </>;
}
