"use client";

import { useMemo, useState } from "react";
import { Button, Metric, PageHeader, Panel, Tag } from "./NgoUI";
import styles from "./NgoFunding.module.css";

const missions=[
 {id:"MSN-2025-00418",status:"Ongoing Field Ops",sponsor:"Tata Clean Urban Mission (CSR)",title:"Yamuna Ghat Plastic Interception & Drain Desilting",place:"Ward 84 • Nigambodh Sector Drain Outfall • Heavy Silt Classification",grant:"₹4,80,000",spent:"₹3,42,800",released:"₹2,40,000",pending:"₹1,44,000",progress:78,costs:[["Suction Jetter Rental","₹1,12,000","4 Days Continuous"],["Safai Sathi Wages","₹1,20,000","12 Workers · 10 Shifts"],["Tipper Fuel (Diesel)","₹45,800","GPS Validated Runs"],["Heavy PPE & Waders","₹32,000","Industrial Chest Waders"],["River Booms & Nets","₹33,000","High-density Polyethylene"]]},
 {id:"MSN-2025-00431",status:"Awaiting CSR Release",sponsor:"Hero Eco-Drive Initiative (CSR)",title:"Old Delhi Railway Station Culvert Desilting & De-choking",place:"Ward 84 • Railway Culvert Gate 3 • Field Operations 100% Completed",grant:"₹1,75,000",spent:"₹1,58,400",released:"₹0",pending:"₹1,58,400",progress:100,costs:[["Desilting & Crew","₹88,000","6 Safai Sathis"],["Suction Jetter","₹42,000","2 Shift Rental"],["Fuel & Transport","₹18,400","GPS Verified"],["Safety PPE","₹10,000","Crew Issue Log"]]},
 {id:"MSN-2025-00412",status:"Funding Completed & Settled",sponsor:"DLF Urban Reclaim Escrow",title:"Seelampur Flyover Pier #12 Underpass Rubble Sweep & Disinfection",place:"Ward 54 • Completed 24 Feb 2025 • Audit Score: 100/100",grant:"₹2,50,000",spent:"₹2,18,500",released:"₹2,50,000",pending:"₹0",progress:100,costs:[["Field Operations","₹1,12,000","Crew and wages"],["Machinery & Fuel","₹68,500","GPS Verified Runs"],["Disinfection & PPE","₹38,000","Safety certified"]]},
 {id:"MSN-2025-00398",status:"Funding Completed & Settled",sponsor:"ITC Mission Sunehra Kal",title:"Ghazipur Wholesale Vegetable Mandi Bio-Waste Segregation",place:"Ward 108 • 18.2 MT Wet Waste Diverted from Landfill",grant:"₹3,20,000",spent:"₹2,94,000",released:"₹3,20,000",pending:"₹0",progress:100,costs:[["Crew Operations","₹1,14,000","10 Safai Sathis"],["Waste Transit","₹96,000","Tipper and fuel"],["Segregation PPE","₹48,000","Safety kit"]]},
];
const tabs=["All Missions (18)","Ongoing (4)","Awaiting CSR Release (4)","Settled & Disbursed (10)"];

export default function NgoFunding(){const [tab,setTab]=useState(tabs[0]);const [query,setQuery]=useState("");const [notice,setNotice]=useState("");
 const visible=useMemo(()=>missions.filter(m=>(tab===tabs[1]?m.status.startsWith("Ongoing"):tab===tabs[2]?m.status.startsWith("Awaiting"):tab===tabs[3]?m.status.startsWith("Funding Completed"):true)&&`${m.title} ${m.id} ${m.sponsor}`.toLowerCase().includes(query.toLowerCase())),[tab,query]);
 return <><PageHeader eyebrow="Funding Updates & CSR Escrow Ledger" title="Funding Updates & CSR Reimbursement" description="Real-time municipal-verified CSR escrow disbursement, NGO operational cost claims, and milestone settlements across active and certified sanitation missions." actions={<><Tag tone="green">◉ RBI Escrow Linked</Tag><Button variant="plain" onClick={()=>setNotice("Weighbridge reconciliation started (mock)")}>▣ Reconcile Weighbridge</Button><Button variant="plain" onClick={()=>setNotice("Audit CSV export prepared (mock)")}>↓ Export Audit CSV</Button><Button onClick={()=>setNotice("New cost claim form opened (mock)")}>⊕ Submit Cost Claim</Button></>}/>
 <div className={styles.metrics}><Metric label="Total CSR committed" value="₹48.50 Lakhs" detail="94% Escrow Locked · 8 Corporate ESG Partners"/><Metric label="Costs incurred by NGO" value="₹34.20 Lakhs" detail="Fleet, wages, fuel & utilities" tone="blue" icon="▰"/><Metric label="Awaiting CSR release" value="₹6.80 Lakhs" detail="4 missions in review · MCD dual-sign" tone="red" icon="⌛"/><Metric label="Settled & disbursed" value="₹27.40 Lakhs" detail="100% dual-signed · 10 missions cleared" tone="mint" icon="▣"/></div>
 <Panel className={styles.filters}><div className={styles.tabs}>{tabs.map(item=><button key={item} className={item===tab?styles.active:""} onClick={()=>setTab(item)}>{item}</button>)}</div><div className={styles.filterRow}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕ Search mission, sponsor, claim…"/><select aria-label="CSR sponsor"><option>All CSR Sponsors</option><option>Tata Clean Urban Mission</option><option>DLF Urban Reclaim Escrow</option><option>ITC Mission Sunehra Kal</option></select><select aria-label="Ward filter"><option>Wards: All (54, 84, 108)</option><option>Ward 54</option><option>Ward 84</option><option>Ward 108</option></select><select aria-label="Sort claims"><option>Sort: Claim Amount</option><option>Newest</option></select><Tag tone="gray">FY 2024-25 Q1</Tag></div></Panel>
 {notice&&<div className={styles.notice} role="status">✓ {notice}<button onClick={()=>setNotice("")} aria-label="Dismiss">×</button></div>}
 <div className={styles.layout}><div className={styles.missions}>{visible.map(m=><Panel key={m.id} className={styles.mission}><div className={styles.meta}><Tag tone="blue">#{m.id}</Tag><Tag tone={m.status.startsWith("Ongoing")?"green":m.status.startsWith("Awaiting")?"red":"green"}>{m.status}</Tag></div><Tag tone="green">{m.sponsor}</Tag><h2>{m.title}</h2><p className={styles.place}>⌖ {m.place}</p><div className={styles.grantBox}><small>{m.status.startsWith("Funding Completed")?"SETTLED AMOUNT":"COMMITTED CSR GRANT"}</small><b>{m.status.startsWith("Funding Completed")?m.released:m.grant}</b><span>{m.status.startsWith("Funding Completed")?"Escrow Secured · Audit verified":"Escrow Secured (RBI Node)"}</span></div><div className={styles.spend}><span><small>COSTS INCURRED TO DATE</small><b>{m.spent}</b><i>Paid via NGO Operating Liquidity</i></span><span><small>TRANCHE 1 DISBURSED</small><b>{m.released}</b><i>Settled release</i></span><span><small>AWAITING CSR RELEASE</small><b>{m.pending}</b><i>Requires weighbridge validation</i></span></div><div className={styles.completion}><div><b>Physical Milestone Completion ({m.progress}%)</b><span>Target: 14.5 MT</span></div><div className={styles.bar}><i style={{width:`${m.progress}%`}}/></div></div><div className={styles.ledgerTitle}><b>▤ ITEMIZED OPERATIONAL COST LEDGER (VOUCHERS ATTACHED)</b><button onClick={()=>setNotice(`Receipts ZIP prepared for ${m.id} (mock)`)}>Download All Receipts (.zip)</button></div><div className={styles.costs}>{m.costs.map(([name,value,detail])=><div key={name}><b>{name}</b><strong>{value}</strong><small>{detail}</small></div>)}</div>{m.status.startsWith("Ongoing")?<><p className={styles.contract}>▣ Escrow Contract: #TATA-YAMUNA-ESC-8821</p><div className={styles.actions}><Button variant="soft" onClick={()=>setNotice(`Voucher upload opened for ${m.id} (mock)`)}>Upload New Vouchers</Button><Button onClick={()=>setNotice(`Additional cost entry opened for ${m.id} (mock)`)}>＋ Log Additional Cost</Button></div></>:m.status.startsWith("Awaiting")?<><p className={styles.pending}>! Awaiting MCD Executive Engineer countersignature</p><div className={styles.actions}><Button variant="soft" onClick={()=>setNotice("Itemized invoices opened (mock)")}>▣ View Itemized Invoices</Button><Button variant="danger" onClick={()=>setNotice("Reminder sent to Ward Officer & Escrow Desk (mock)")}>▶ Ping Ward Officer & Escrow Desk</Button></div></>:<div className={styles.actions}><Button variant="soft" onClick={()=>setNotice("Settlement certificate opened (mock)")}>◉ Settlement Certificate</Button><Button onClick={()=>setNotice("Audit ledger PDF prepared (mock)")}>↓ Audit Ledger (PDF)</Button></div>}</Panel>)}{visible.length===0&&<Panel><p className={styles.empty}>No funding records match this view.</p></Panel>}</div>
 <aside className={styles.aside}><Panel><div className={styles.asideHead}><h2>♧ CSR Escrow Pool</h2><b>₹48.50L Pledged</b></div>{[["Tata Clean Urban Mission","₹11.20L / ₹14.50L",77],["DLF Urban Reclaim Escrow","₹9.50L / ₹12.00L",79],["ITC Mission Sunehra Kal","₹8.80L / ₹10.00L",88],["Hero Eco-Drive Initiative","₹4.20L / ₹7.50L",56],["UltraTech Swachh Bharat Trust","₹2.10L / ₹4.50L",47]].map(([name,value,pct])=><div className={styles.poolItem} key={String(name)}><div><b>{name}</b><strong>{value}</strong></div><div className={styles.bar}><i style={{width:`${pct}%`}}/></div><small>{pct}% Settled</small></div>)}<p className={styles.lock}>♙ All grants are auto-locked in tripartite RBI escrow vaults released upon MCD Municipal Engineer dual sign-off.</p></Panel><Panel><div className={styles.asideHead}><h2>♧ Action Items Required</h2><Tag tone="red">2 Urgent</Tag></div><div className={styles.actionItem}><b>MCD Weighbridge Countersign</b><small>Slip #WB-DEL-8902 requires Ghazipur gate supervisor stamp to release ₹1,58,400 CSR escrow.</small><Button variant="danger" onClick={()=>setNotice("Alert resent to Ward 84 supervisor (mock)")}>Resend Alert to Ward 84 SE</Button></div><div className={styles.actionItem}><b>Fuel Telemetry Discrepancy</b><small>Tipper #DL-1GC-4491 logged 38 km without GPS heartbeat during Yamuna Ghat night haul.</small><Button variant="soft" onClick={()=>setNotice("Driver logbook review opened (mock)")}>Submit Driver Logbook</Button></div></Panel><Panel><h2 className={styles.asideTitle}>◉ NGO Cost Distribution</h2><div className={styles.stacked}><i/><i/><i/><i/><i/></div>{[["Heavy Machinery & Fleet Rental","38%","₹13.00L"],["Field Safai Sathi Direct Wages","35%","₹11.97L"],["Weighbridge Gate & Landfill Fees","15%","₹5.13L"],["Disinfection Lime & Bio-Enzyme Sprays","8%","₹2.74L"],["Safety Gear, Respirators & Waders","4%","₹1.36L"]].map((row,i)=><div className={styles.distribution} key={row[0]}><i className={styles[`dot${i}`]}/> <span>{row[0]}</span><b>{row[1]} ({row[2]})</b></div>)}</Panel><Panel className={styles.escalation}><small>MCD ESCROW DESK</small><h2>Disbursement Escalations</h2><p>Have an unreleased claim exceeding the 72-hour audit SLA window? Connect directly with the Joint Municipal Commissioner Desk.</p><b>1800-244-SAAF <small>EXT 44</small></b></Panel></aside></div>
 </>;
}
