"use client";

import { useMemo, useState } from "react";
import { Button, Metric, PageHeader, Panel, Tag } from "./NgoUI";
import styles from "./NgoReports.module.css";

const reports=[
 {id:"REP-2025-09418",ward:"Ward 84",place:"Yamuna Ring Road Culvert (28.6658° N, 77.2341° E)",age:"18 mins ago",severity:"CRITICAL SEVERITY",title:"Ward 84 • Yamuna Ring Road Culvert Inflow — Severe Plastic Choke & Storm Sludge",description:"Dense blockage obstructing 85% culvert outflow into Yamuna flood basin. High probability of road back-flooding within 4 hours if not intercepted.",score:98,type:"Plastic & Silt",image:"/citizen/report-overview.png",volunteers:"14 Volunteers on Standby",grant:"₹36,500",status:"AI Recommended",tone:"green"},
 {id:"REP-2025-09382",ward:"Ward 54",place:"Seelampur Market Back-Alley (28.6720° N, 77.2750° E)",age:"42 mins ago",severity:"CRITICAL SEVERITY",title:"Ward 54 • Seelampur Market Back-Alley — Chronic Dump Spillover & Rotten Organic Waste",description:"Severe organic refuse fermentation from vegetable vendor runoff mixed with C&D rubble. Heavy odor and vector contamination risk adjacent to government dispensary.",score:94,type:"Bio-Waste",image:"/citizen/report-debris.png",volunteers:"8 Volunteers Nearby",grant:"₹28,000",status:"AI Recommended",tone:"green"},
 {id:"REP-2025-09355",ward:"Ward 108",place:"Ghazipur Mandi Outer Gate Bypass",age:"1h 10m ago",severity:"MEDIUM SEVERITY",title:"Ward 108 • Ghazipur Mandi Outer Gate Bypass — Bulk Commercial Carton & Wooden Crates",description:"Recyclables dry load. Suitable for a small pickup crew and material recovery route.",score:82,type:"Recyclables",image:"/citizen/report-debris.png",volunteers:"5 Volunteers Nearby",grant:"₹14,000",status:"New Report",tone:"blue"},
 {id:"REP-2025-09310",ward:"Ward 42",place:"Mori Gate Commercial Outer",age:"2h 05m ago",severity:"HAZMAT / LOW NGO MATCH",title:"Ward 42 • Mori Gate Chemical Drum Leakage & Industrial Slurry",description:"Requires Hazmat Level-B PPE and specialized solvent treatment. DPCC intervention recommended.",score:38,type:"Hazardous",image:"/citizen/report-drain.png",volunteers:"Specialist response required",grant:"—",status:"Outside NGO Scope",tone:"red"},
];
const tabs=["All Reports (38)","AI Recommended for Us (12)","Critical Severity (9)","Under 3 km (16)","Plastic & Silt Focus (14)","Bio-Waste"];

export default function NgoReports(){const [tab,setTab]=useState(tabs[0]);const [query,setQuery]=useState("");const [notice,setNotice]=useState("");const [accepted,setAccepted]=useState<string[]>([]);
 const visible=useMemo(()=>reports.filter(item=>(tab===tabs[1]?item.score>=90:tab===tabs[2]?item.severity.startsWith("CRITICAL"):tab===tabs[4]?item.type==="Plastic & Silt":tab===tabs[5]?item.type==="Bio-Waste":true)&&`${item.id} ${item.ward} ${item.title} ${item.place}`.toLowerCase().includes(query.toLowerCase())),[tab,query]);
 const accept=(id:string)=>{setAccepted(current=>[...current,id]);setNotice(`${id} accepted and crew dispatch queued (mock).`);};
 return <><PageHeader eyebrow="Cleanliness Grievance & Incident Reports" title="Nearby Cleanliness Reports & AI Dispatch Triage" description="Real-time verified citizen and sensor reports across assigned operational wards (Ward 54 Seelampur, Ward 84 Kashmere Gate, Ward 108 Ghazipur). Powered by computer vision severity diagnostics, resource requirement projections, and NGO capability match algorithms." actions={<><Button variant="plain" onClick={()=>setNotice("Ward filters opened (mock)")}>☷ Filter Wards</Button><Button variant="plain" onClick={()=>setNotice("Report export prepared (mock)")}>↓ Export CSV</Button><Button onClick={()=>setNotice("Three recommended cases queued for batch acceptance (mock)")}>ϟ Batch Accept Recommended (3)</Button></>}/>
 <div className={styles.metrics}><Metric label="Total nearby reports" value="38 Open" detail="9 Critical · 14 within 2.5 km" tone="red"/><Metric label="AI capability match" value="12 Optimal" detail="Matches jetter & manual teams"/><Metric label="Avg citizen triage SLA" value="2h 15m" detail="98.2% Compliance · Within target" tone="blue" icon="◷"/><Metric label="Allocated CSR escrow" value="₹14.20L" detail="Instant Lock Ready · Tata Clean Urban" tone="green"/></div>
 <Panel className={styles.filterPanel}><div className={styles.filters}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="⌕  Search by landmark, ticket #, reporter, or waste category"/><select aria-label="Sort reports"><option>Sort: AI Match Score (Highest first)</option><option>Newest first</option><option>Critical first</option></select><select aria-label="Radius"><option>Radius: Within 5 km</option><option>Within 2 km</option><option>All assigned wards</option></select></div><div className={styles.tabs}>{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={item===tab?styles.selected:""}>{item}</button>)}</div></Panel>
 {notice&&<div className={styles.notice} role="status">✓ {notice}<button onClick={()=>setNotice("")} aria-label="Dismiss">×</button></div>}
 <div className={styles.layout}><div className={styles.list}>{visible.map(report=><Panel key={report.id} className={styles.report}><div className={styles.reportMeta}><Tag tone="blue">#{report.id}</Tag><span>⌖ {report.ward} • {report.place}</span><small>• {report.age}</small></div><div className={styles.status}><Tag tone={report.tone as "green"|"red"|"blue"}>{report.severity}</Tag>{accepted.includes(report.id)&&<Tag tone="green">Accepted</Tag>}</div><h2>{report.title}</h2><p className={styles.description}>{report.description}</p><div className={`${styles.recommendation} ${report.tone==="red"?styles.alert:""}`}><span className={styles.recommendIcon}>♧</span><div><b>✦ {report.score}% AI Capability Match <Tag tone={report.score>90?"green":"yellow"}>{report.score>90?"Highly Recommended":"Review Match"}</Tag></b><p>{report.score>90?"Matches certified field equipment and volunteer capacity. Recommended team can mobilize within SLA.":"Review location, waste category, and available team before accepting."}</p></div><Button variant={report.tone==="red"?"danger":"primary"} onClick={()=>report.score>60?accept(report.id):setNotice("This case needs specialist hazmat support (mock)")}>{report.score>60?"✓ Accept & Mobilize":"Auto-escalate to DPCC"}</Button></div><details className={styles.diagnostics} open={report.score>90}><summary>AI DIAGNOSTICS, FIELD PHOTOS & RESOURCE ESTIMATES</summary><div className={styles.evidence}><div className={styles.imageCard}><img src={report.image} alt={`${report.type} field evidence`}/><span>Citizen Photo · Meera Kapoor +30</span><small>◉ 28.6658° N, 77.2341° E · ±1.5m</small></div><div className={styles.aiImage}><img src="/citizen/report-drain.png" alt="AI waste material segmentation preview"/><span>▧ AI Material Segmentation</span></div><div className={styles.estimate}><small>WASTE DIAGNOSTIC SPECTRUM</small><b>{report.type} / Sludge <strong>{report.score>90?62:38}%</strong></b><div className={styles.spectrum}><i style={{width:`${report.score>90?62:38}%`}}/></div><p>Volume: 3.8 MT <b>CSR FUNDING LOCK {report.grant}</b></p></div></div><div className={styles.resource}><span><small>CREW & MACHINERY NEED</small><b>10 Safai Sathis + 1 Supervisor</b><i>1× Suction Jetter · 1× 4-Ton Tipper Truck</i></span><span><small>DEPLOYMENT WINDOW</small><b>3h 30m Duration</b><i>14 Volunteers on Standby</i></span><span><small>CSR FUNDING LOCK</small><b>{report.grant} Pre-approved</b><i>Tata Clean Urban Mission</i></span></div></details><div className={styles.reportFooter}><span>♢ Municipal SLA Priority Guarantee: 2h 45m Response Deadline</span><div><Button variant="soft" onClick={()=>setNotice(`Volunteer notification sent for ${report.id} (mock)`)}>♧ Notify Volunteers</Button><Button onClick={()=>accept(report.id)}>▶ Accept & Dispatch Crew #03</Button></div></div></Panel>)}{visible.length===0&&<Panel><p className={styles.empty}>No reports match these filters.</p></Panel>}</div>
 <aside className={styles.aside}><Panel><div className={styles.asideTitle}><h2>♧ Fleet Readiness</h2><Tag tone="green">Active Live</Tag></div><div className={styles.readiness}><b>Ready Crew Teams</b><strong>3 Teams Free (12 Safai Sathis)</strong></div><div className={styles.bar}><i/></div>{[["♧","Suction Jetter #SJ-02","Standby (1.4km)"],["▰","Tipper Truck 4-Ton #TT-01","Ready"],["⚒","JCB Loader #JC-04","Busy till 11:30 AM"]].map(item=><div className={styles.fleet} key={item[1]}><b>{item[0]}</b><span><strong>{item[1]}</strong><small>{item[2]}</small></span></div>)}<p className={styles.jurisdiction}>Active Geo-Fenced Jurisdiction<br/><b>Ward 54, Ward 84, Ward 108</b></p></Panel><Panel><h2 className={styles.asideTitle}>♧ AI Optimal Batch</h2><p className={styles.description}>Accepting both #REP-09418 (Yamuna Culvert) and #REP-09382 (Seelampur) will achieve 100% daily yard turnaround quota and unlock ₹64,500 in CSR escrow claims before 2:00 PM.</p><Button onClick={()=>setNotice("Two top recommended reports accepted in mock batch")}>✓ Dispatch 2 Recommended</Button></Panel><Panel><div className={styles.asideTitle}><h2>Recent Decision Log</h2><button onClick={()=>setNotice("Decision history opened (mock)")}>View History</button></div>{[["#REP-09294 Yamuna Ghat #4","Accepted · Crew #01 (Lead: Anil Kumar)","₹22,000"],["#REP-09277 Anand Vihar Drain","Declined · Rerouted to MCD Depot","Out of Ward"],["#REP-09251 Seelampur Metro G-2","Completed · Verified by 19 Citizens","₹31,500"]].map(item=><div className={styles.log} key={item[0]}><b>{item[0]}</b><span>{item[1]}</span><strong>{item[2]}</strong></div>)}</Panel></aside></div>
 </>;
}
