"use client";

import { useMemo, useState } from "react";
import { Button, Metric, PageHeader, Panel, Tag } from "./NgoUI";
import styles from "./NgoVolunteers.module.css";

type Volunteer={id:string;name:string;age:string;badge:string;badgeTone:"red"|"blue"|"green";place:string;distance:string;applied:string;skill:string;skills:string;equipment:string;availability:string;mission:string;avatar:string;status:string};
const initial:Volunteer[]=[
 {id:"aakash",name:"Aakash Verma",age:"24 yrs",badge:"NEW APPLICANT",badgeTone:"red",place:"Kashmere Gate (Ward 84)",distance:"0.8 km from Yamuna Ghat MSN #00418",applied:"Applied 3h ago",skill:"Preferred Missions",skills:"Plastic Interception & Riverbank Cleanups, Storm Drains",equipment:"Heavy rubber chest waders, 2-way VHF radio, rubberized gauntlets",availability:"Immediate Standby · Morning Shift (07:00 AM – 12:00 PM)",mission:"Yamuna Ghat Plastic Interception (Needs 4)",avatar:"AV",status:"Pending"},
 {id:"meena",name:"Meenakshi Sundaram",age:"31 yrs",badge:"VEHICLE OWNER",badgeTone:"blue",place:"Seelampur (Ward 54)",distance:"1.4 km from Flyover Underpass",applied:"Active member · 6 missions",skill:"Equipment & Transit",skills:"Tata Ace Mini-Tipper (Seats 6 volunteers + 500kg wet load capacity)",equipment:"Commercial Market Waste Sweeps, Lime & Disinfectant Transit",availability:"Full-day on call · Trans-Yamuna / NCT East Zone",mission:"Seelampur Flyover Rubble Sweep (Needs 2)",avatar:"MS",status:"Available"},
 {id:"tariq",name:"Tariq Nadeem",age:"27 yrs",badge:"STANDBY POOL",badgeTone:"green",place:"Old Delhi (Ward 84)",distance:"1.9 km from Railway Culvert",applied:"18 missions · 4.9★",skill:"Core Specialization",skills:"Mechanized Desilting, Suction Hose Guidance, Silt Trap Extraction",equipment:"MCD Confined Spaces & Gas Detector Safety Trained",availability:"Standby check-in at 07:15 AM",mission:"MSN-2025-00431 · Railway Culvert Desilting",avatar:"TN",status:"Available"},
 {id:"pooja",name:"Pooja Sharma",age:"29 yrs",badge:"IN FIELD (ACTIVE)",badgeTone:"green",place:"Ghazipur Mandi (Ward 108)",distance:"MSN-2025-00398 · Active mission",applied:"Check-in 07:42 AM",skill:"Bio-Waste Specialist",skills:"Organic waste segregation and composting",equipment:"Shift target: 1.2 Tons Organic Waste Segregation",availability:"Expected release 11:30 AM",mission:"Ward 108 Mandi Bio-Waste Segregation",avatar:"PS",status:"Deployed"},
 {id:"rohan",name:"Rohan Malhotra",age:"22 yrs",badge:"NEW APPLICATION",badgeTone:"red",place:"Seelampur / Shahdara (Ward 54)",distance:"Applied 14h ago",applied:"DU Eco Club",skill:"Preference & Capacity",skills:"Door-to-door Segregation Awareness, Anti-Littering Street Plays",equipment:"Can mobilize 12 university student volunteers on Saturday / Sunday",availability:"Weekend Pool",mission:"Community Anti-Dumping Drive · Ward 54",avatar:"RM",status:"Pending"},
];
const tabs=["All Volunteers (148)","Pending Review (16)","Available Standby (38)","Currently Deployed (54)"];

export default function NgoVolunteers(){const [people,setPeople]=useState(initial);const [tab,setTab]=useState(tabs[0]);const [query,setQuery]=useState("");const [notice,setNotice]=useState("");
 const visible=useMemo(()=>people.filter(p=>(tab===tabs[1]?p.status==="Pending":tab===tabs[2]?p.status==="Available":tab===tabs[3]?p.status==="Deployed":true)&&`${p.name} ${p.place} ${p.skills}`.toLowerCase().includes(query.toLowerCase())),[people,tab,query]);
 function action(id:string,mode:"assign"|"standby"){setPeople(list=>list.map(person=>person.id===id?{...person,status:mode==="assign"?"Deployed":"Available"}:person));const person=people.find(item=>item.id===id);setNotice(`${person?.name??"Volunteer"} ${mode==="assign"?"assigned to mission":"added to standby pool"} (mock).`);}
 return <><PageHeader eyebrow="Volunteers & Mobilization Hub" title="Volunteer Roster & Mission Dispatch" description="Review incoming citizen profiles, match field preferences with ongoing sanitation interventions, and deploy verified taskforces across Wards 54, 84, and 108." actions={<><Button onClick={()=>setNotice("Mobilization broadcast composed (mock)")}>◉ Broadcast Mobilization</Button><Button variant="soft" onClick={()=>setNotice("Walk-in volunteer form opened (mock)")}>♧ Walk-in Volunteer</Button><Button variant="plain" onClick={()=>setNotice("Roster export prepared (mock)")}>↓ Export</Button></>}/>
 <div className={styles.metrics}><Metric label="Registered volunteers" value="148" detail="+18 this week · 134 eKYC verified"/><Metric label="Active standby (<3km)" value="38" detail="Ready for immediate dispatch" tone="mint" icon="ϟ"/><Metric label="Currently deployed" value="54" detail="12 active teams · Yamuna & Underpasses" tone="blue" icon="♧"/><Metric label="Pending intake" value="16" detail="Action required · Applied <24h ago" tone="red" icon="▣"/></div>
 <Panel className={styles.filter}><div className={styles.tabs}>{tabs.map(item=><button key={item} className={item===tab?styles.active:""} onClick={()=>setTab(item)}>{item}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕  Name, ward, skill, phone…"/><select aria-label="Assigned wards"><option>All Wards (54, 84, 108)</option><option>Ward 54</option><option>Ward 84</option><option>Ward 108</option></select><select aria-label="Preferences"><option>All Preferences</option><option>Desilting</option><option>Bio-waste</option></select></Panel>
 {notice&&<div className={styles.notice} role="status">✓ {notice}<button onClick={()=>setNotice("")} aria-label="Dismiss">×</button></div>}
 <div className={styles.layout}><div className={styles.people}>{visible.map(person=><Panel key={person.id} className={styles.person}><div className={`${styles.edge} ${person.badgeTone===`red`?styles.red:person.badgeTone===`blue`?styles.blue:styles.green}`}/><header className={styles.personHeader}><i className={styles.avatar}>{person.avatar}</i><div className={styles.personIntro}><div><h2>{person.name}</h2><span>• {person.age}</span><Tag tone={person.badgeTone}>{person.badge}</Tag><Tag tone="green">✓ Govt ID Verified</Tag></div><p>⌖ {person.place} <b>· {person.distance}</b> <span>· {person.applied}</span></p></div><div className={styles.contact}><button onClick={()=>setNotice(`Calling ${person.name} (mock)`)} aria-label={`Call ${person.name}`}>☎</button><button onClick={()=>setNotice(`Message to ${person.name} opened (mock)`)} aria-label={`Message ${person.name}`}>▤</button></div></header><div className={styles.details}><div><b>♧ {person.skill}</b><p>{person.skills}</p></div><div><b>⚒ Equipment Owned / Experience</b><p>{person.equipment}</p></div><small>◷ {person.availability}</small></div><footer className={styles.assignment}><span>☑　{person.mission}</span>{person.status==="Deployed"?<Tag tone="blue">Currently Deployed</Tag>:<><Button onClick={()=>action(person.id,"assign")}>{person.equipment.includes("Tipper")?"▰ Deploy Vehicle & Driver":"✓ Accept & Assign"}</Button><Button variant="soft" onClick={()=>action(person.id,"standby")}>Standby Only</Button></>}</footer></Panel>)}{visible.length===0&&<Panel><p className={styles.empty}>No volunteers found for this view.</p></Panel>}</div>
 <aside className={styles.aside}><Panel><div className={styles.asideHead}><h2>Active Mission Quotas</h2><Tag tone="red">9 Deficit</Tag></div><p className={styles.intro}>Currently executed operations requiring additional volunteer hand power today.</p>{[["URGENT · NEED 4","MSN-2025-00418: Yamuna Ghat Plastic Interception","Ward 84 · Kashmere Gate Ghat #3",8,12,"Riverbank Boom & Desilt"],["NEED 2 VOLUNTEERS","MSN-2025-00412: Seelampur Underpass Rubble","Ward 54 · Pier #12 Disinfection",10,12,"Lime Disinfection Spray"],["NEED 3 VOLUNTEERS","MSN-2025-00431: Old Delhi Railway Culvert","Ward 84 · Heavy Silt Clean",3,6,"Mechanical Hose Guidance"]].map(([label,title,place,have,total,skill])=><div className={styles.quota} key={String(title)}><div><Tag tone={String(label).startsWith("URGENT")?"red":"green"}>{label}</Tag><b>{have} / {total}</b></div><strong>{title}</strong><small>{place}</small><div className={styles.bar}><i style={{width:`${Number(have)/Number(total)*100}%`}}/></div><p>Specialty: {skill}<button onClick={()=>setNotice(`Quick dispatch roster opened for ${title} (mock)`)}>Quick Dispatch　→</button></p></div>)}</Panel><Panel><h2 className={styles.asideTitle}>Roster Skill Readiness</h2>{[["Waste Segregation & Composting",45,"30%"],["Plastic Riverbank Interception",38,"26%"],["Heavy Culvert & Drain Desilting",24,"16%"],["First Aid / Safety Marshals",18,"12%"],["Vehicle & Tipper Owners",12,"8%"]].map(([label,count,percent])=><div className={styles.skill} key={String(label)}><div><b>{label}</b><strong>{count} volunteers ({percent})</strong></div><div className={styles.bar}><i style={{width:String(percent)}}/></div></div>)}</Panel><Panel className={styles.broadcast}><h2>◉ Instant Dispatch Broadcast</h2><p>Send localized SMS & app push to standby volunteers.</p><label>Target Radius / Ward<select><option>Ward 84 (Kashmere Gate / Yamuna) — 18 standby</option><option>Ward 54 (Seelampur) — 12 standby</option><option>Ward 108 (Ghazipur) — 8 standby</option></select></label><label>Mobilization Message Template<textarea defaultValue="SAAF Civic Alert: Urgent volunteer mobilization for Yamuna Ghat plastic interception (MSN-00418). Assemble at 07:30 AM near Kashmere Gate Ghat #3."/></label><Button onClick={()=>setNotice("Instant push and SMS alert sent (mock)")}>▶ Send Instant Push & SMS Alert</Button></Panel></aside></div>
 </>;
}
