"use client";
import { useState } from "react";
import Link from "next/link";
import { Eyebrow, Icon, PortalFooter, PortalHeader } from "./PortalShell";
import styles from "./CitizenDashboard.module.css";

const activities = [
  { icon:"PN", title:"Priya N. reported silting at Sluice #84-B", detail:"Civil Lines · Block A · Assigned to Safai Shakti NGO Team A", badge:"78% Cleared", time:"14 mins ago", type:"report" },
  { icon:"♧", title:"Weekend Drive at Kashmere Gate Bus Terminal", detail:"Targeting plastic recovery & segregated waste bins setup", badge:"18 Signed Up (4 spots left)", time:"Today", type:"drive" },
  { icon:"✓", title:"Resolved: Mori Gate Alley cleared & disinfected", detail:"Municipal mechanized wash completed · Before/After Verified", badge:"Closed Ticket #MCD-8409", time:"1h ago", type:"report" },
];

export default function CitizenDashboard() {
  const [tab,setTab]=useState("Hub Overview");
  return <div className={styles.page}><PortalHeader active={tab}/><main>
    <section className={styles.welcome}><div className={styles.node}><span>●</span> SAAF Civic Node Active <i>•</i> Ward 84 · Kashmere Gate &amp; Civil Lines, Central Delhi</div><div className={styles.protocol}>♧ MUNICIPAL VERIFICATION PROTOCOL V3.4</div><div className={styles.welcomeRow}><div><Eyebrow>CITIZEN ACTION CONSOLE</Eyebrow><h1>Welcome back, <em>Aarav!</em></h1><p>What would you like to accomplish today? Your civic vigilance keeps Ward 84 spotless, safe,<br className={styles.desktopBreak}/> and accountable.</p></div><div className={styles.scorecard}><div><span className={styles.scoreIcon}>✓</span><b>4<small>Reports (3 Done)</small></b></div><div><span className={styles.scoreIcon}>♧</span><b>8h<small>2 Drives Attended</small></b></div><strong>✳ Level 2 Guardian<small>320 Karma Points</small></strong></div></div></section>
    <section className={styles.actions}>
      <article className={styles.actionCard}><div className={styles.cardHead}><span className={styles.reportPill}>✣ AI-Powered Triage &amp; Geotag</span><small>Pillar 01 · SPOT</small></div><h2>Report Sanitation Issue</h2><p>Spot overflowing garbage, illegal construction debris, choked stormwater drains, or hazardous open sewage in seconds.</p><div className={styles.features}><div><Icon>▣</Icon><span><b>Instant Photo &amp; AI</b><small>Auto-detects waste category, volume &amp; tonnage</small></span></div><div><Icon>♧</Icon><span><b>Automatic Geotag</b><small>Precise GPS coordinates mapped straight to Ward 84</small></span></div><div><Icon>▤</Icon><span><b>WhatsApp / SMS Track</b><small>Step-by-step photograph clearance verification</small></span></div><div><Icon>✓</Icon><span><b>Evidence-backed Updates</b><small>Know when a municipal team is dispatched</small></span></div></div><div className={styles.photo}><img src="/citizen/dashboard-report.png" alt="Municipal sanitation truck in Central Delhi"/><span>Central Delhi Municipal Fleet Node Active</span><b>Avg dispatch: 24m</b></div><div className={styles.cardActions}><Link href="/report" className={styles.primary}>Start New Report　→</Link><Link href="#activity">View My 4 Previous Reports　›</Link></div></article>
      <article className={styles.actionCard}><div className={styles.cardHead}><span className={styles.volunteerPill}>♧ Community Taskforce &amp; Drives</span><small>Pillar 02 · ACT</small></div><h2>Join as a Volunteer</h2><p>Lend a hand in neighborhood cleanup drives, segregation campaigns, or mechanized desilting taskforces this weekend.</p><div className={styles.features}><div><Icon>♢</Icon><span><b>Accredited Civic NGOs</b><small>Partner with Safai Shakti Guild &amp; CleanCity Alliance</small></span></div><div><Icon>✓</Icon><span><b>Free Safety Gear &amp; PPE</b><small>Heavy-duty gloves, particulate masks &amp; high-vis vests</small></span></div><div><Icon>♧</Icon><span><b>Official Civic Certificate</b><small>Verified volunteer service credit recognized by MCD</small></span></div><div><Icon>▣</Icon><span><b>Ward Logistics Provided</b><small>Hydration, clean snacks, and community transport</small></span></div></div><div className={`${styles.photo} ${styles.volunteerPhoto}`}><img src="/citizen/dashboard-volunteers.png" alt="Local volunteers at a Delhi neighborhood cleanup"/><span>Next Drive: Kashmere Gate Bus Terminal</span><b>This Saturday · 07:30 AM</b></div><div className={styles.cardActions}><Link href="/volunteer" className={styles.primary}>Explore Volunteer Drives　♧</Link><Link href="/volunteer">Update Profile &amp; Skills　›</Link></div></article>
    </section>
    <section className={styles.neighborhood} id="impact"><div className={styles.neighborhoodTitle}><div><Eyebrow>♧ HYPERLOCAL INTELLIGENCE</Eyebrow><h2>Your Neighborhood at a Glance</h2><p>Live telemetry and communal activity tracked in Ward 84 (Kashmere Gate · Mori Gate · Civil Lines).</p></div><small>◌ Live feed synced 2m ago</small></div><div className={styles.kpis}>{[["NEARBY ACTIVE MISSIONS","3 Drives","Underway within 2 km radius","△ Closest is 650m from your saved address"],["AVERAGE RESOLUTION SPEED","3.8 Hours","From initial photo capture to confirmed sanitation clearance.","↘ 42 mins faster than municipal SLA norm"],["COMMUNITY CLEAN SCORE","94.2%","Ward 84 sustained sanitation compliance index this month.","♙ Ranked #2 across Central Delhi Zone"]].map(([a,b,c,d],i)=><article key={a}><div className={styles.kpiTop}><small>{a}</small><Icon tone={i===1?"blue":"green"}>{["♧","◷","✳"][i]}</Icon></div><b>{b}</b><p>{c}</p><span>{d}</span></article>)}</div></section>
    <section className={styles.feed} id="activity"><div className={styles.feedHeading}><h2>▤ Recent Ward Activity &amp; Live Feed</h2><div><button onClick={()=>setTab(tab==="Hub Overview"?"My Reports":"Hub Overview")}>{tab === "My Reports" ? "My Reports" : "All Activity"}</button><small>Autorefresh enabled</small></div></div><div className={styles.feedRows}>{activities.map((activity,i)=><article key={activity.title} className={tab==="My Reports"&&activity.type!=="report"?styles.hidden:""}><span className={`${styles.activityIcon} ${i===2?styles.done:""}`}>{activity.icon}</span><div><b>{activity.title}</b><small>{activity.detail}</small></div><strong>{activity.badge}</strong><time>{activity.time}</time></article>)}</div></section>
  </main><PortalFooter/></div>;
}
