import Link from "next/link";
import Image from "next/image";
import styles from "./PublicSiteShell.module.css";

const nav=[["Live Hotspots","/#hotspots"],["How It Works","/#how-it-works"],["Role Portals","/#roles"],["Impact Ledger","/#impact"],["Volunteer Corps","/volunteer"]] as const;

export function PublicSiteHeader(){return <><div className={styles.official}><span><i/> OFFICIAL PILOT　Delhi NCT Urban Sanitation Modernization &amp; Accountability Framework</span><span>Emergency Dispatch: 1800-SAN-DELHI　 <b>◉ MCD Verified Network</b></span></div><header className={styles.header}><Link href="/" className={styles.brand}><Image src="/citizen/saaf-logo.png" alt="SAAF" width={34} height={34}/><span><b>SAAF</b><small>DELHI<br/>NCT</small></span></Link><nav className={styles.nav}>{nav.map(([label,href])=><Link key={label} href={href}>{label}</Link>)}</nav><div className={styles.actions}><Link href="/entry" className={styles.login}>Login / Register</Link><Link href="/report" className={styles.report}>⚑ Report Issue</Link><Link href="/entry" className={styles.account} aria-label="Select portal">♙</Link></div><details className={styles.mobileMenu}><summary aria-label="Open navigation">☰</summary><nav>{nav.map(([label,href])=><Link key={label} href={href}>{label}</Link>)}<Link href="/entry">Login / Register</Link><Link href="/report">Report Issue</Link></nav></details></header></>}

export function PublicSiteFooter(){return <footer className={styles.footer}><div className={styles.footerGrid}><div><Link href="/" className={styles.footerBrand}><Image src="/citizen/saaf-logo.png" alt="" width={30} height={30}/><b>SAAF</b></Link><p>Decentralized public sanitation verification, municipal response orchestration, and ward-level accountability across National Capital Territory of Delhi.</p><strong>◇ Public Utility Digital Standard</strong></div><div><b>Public Portals</b><Link href="/#hotspots">Ward Hotspot Map</Link><Link href="/report">Citizen Issue Reporting</Link><Link href="/portal">Public SLA Ledger</Link><Link href="/volunteer">Delhi Volunteer Corps</Link></div><div><b>Institutional Nodes</b><Link href="/entry">Citizen Verification</Link><Link href="/entry">MCD Ward Administrators</Link><Link href="/ngo">NGO &amp; Sanitation Guilds</Link><Link href="/entry">CSR Infrastructure Funders</Link></div><div><b>Governance &amp; Pilot</b><p>Deployed across 272 MCD Wards, New Delhi Municipal Council, and Delhi Cantonment Board zones.</p><div className={styles.footerSla}><b>Grievance Redressal SLA</b><span>Routine: 24h · Critical: 4h response standard</span></div></div></div><div className={styles.legal}><span>© 2025 SAAF Civic Foundation · Government of NCT of Delhi Public Sandbox.</span><span>Privacy Policy　 Open Data API　 System Status</span></div></footer>}
