"use client";
import { ChangeEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Eyebrow, Icon, PortalFooter, PortalHeader } from "./PortalShell";
import styles from "./ReportPage.module.css";

type ReportPhoto={id:string;file:File;src:string};
type SavedPhoto={id:string;file:File}|null;
type ReportDraft={category:string;severity:string;note:string;photos:SavedPhoto[];latitude:number|null;longitude:number|null;address:string};
const DRAFT_DB="saaf-citizen-drafts";
function openDraftDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DRAFT_DB,1);request.onupgradeneeded=()=>request.result.createObjectStore("drafts");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function readDraft():Promise<ReportDraft|null>{const db=await openDraftDb();return new Promise((resolve,reject)=>{const request=db.transaction("drafts","readonly").objectStore("drafts").get("report");request.onerror=()=>{db.close();reject(request.error);};request.onsuccess=()=>{resolve(request.result??null);db.close();};});}
async function writeDraft(draft:ReportDraft):Promise<void>{const db=await openDraftDb();return new Promise((resolve,reject)=>{const transaction=db.transaction("drafts","readwrite");transaction.objectStore("drafts").put(draft,"report");transaction.oncomplete=()=>{db.close();resolve();};transaction.onerror=()=>{db.close();reject(transaction.error);};transaction.onabort=()=>{db.close();reject(transaction.error);};});}
async function deleteDraft():Promise<void>{const db=await openDraftDb();return new Promise((resolve,reject)=>{const transaction=db.transaction("drafts","readwrite");transaction.objectStore("drafts").delete("report");transaction.oncomplete=()=>{db.close();resolve();};transaction.onerror=()=>{db.close();reject(transaction.error);};transaction.onabort=()=>{db.close();reject(transaction.error);};});}

const categories=["Overflowing Garbage Dump","C&D Debris (Construction)","Choked Storm Drain","Hazardous / Bio-Medical","Open Sewage Leak","Public Toilet Disrepair"];

export default function ReportPage(){
  const [category,setCategory]=useState(categories[0]);const [severity,setSeverity]=useState("Urgent / Obstruction");const [note,setNote]=useState("");const [success,setSuccess]=useState(false);const [photos,setPhotos]=useState<(ReportPhoto|null)[]>([null,null,null]);const [photoError,setPhotoError]=useState("");const [latitude,setLatitude]=useState<number|null>(null);const [longitude,setLongitude]=useState<number|null>(null);const [geoStatus,setGeoStatus]=useState("Location not captured · use your device GPS");const [address,setAddress]=useState("Near Sluice Gate #84-B, Ring Road Underpass, Civil Lines");const [draftStatus,setDraftStatus]=useState("");const [restored,setRestored]=useState(false);const uploadedCount=photos.filter(Boolean).length;
  useEffect(()=>{let active=true;readDraft().then(draft=>{if(!active)return;if(draft){setCategory(draft.category);setSeverity(draft.severity);setNote(draft.note);setLatitude(draft.latitude);setLongitude(draft.longitude);setGeoStatus(draft.latitude!==null&&draft.longitude!==null?"Saved GPS coordinates restored":"Location not captured · use your device GPS");setAddress(draft.address);setPhotos(draft.photos.map(photo=>photo?{...photo,src:URL.createObjectURL(photo.file)}:null));setDraftStatus("Saved draft restored from this device");}setRestored(true);}).catch(()=>{if(active){setDraftStatus("Draft storage is unavailable in this browser");setRestored(true);}});return()=>{active=false;};},[]);
  function captureLocation(){if(!navigator.geolocation){setGeoStatus("This browser does not support GPS location. Enter the landmark below.");return;}setGeoStatus("Requesting device location permission…");navigator.geolocation.getCurrentPosition(position=>{setLatitude(position.coords.latitude);setLongitude(position.coords.longitude);setGeoStatus(`GPS captured · ±${Math.round(position.coords.accuracy)} m accuracy`);},error=>{const message=error.code===1?"Location permission denied. Allow location access in browser settings or enter the landmark below.":error.code===2?"Your position is unavailable. Try again outdoors or enter the landmark below.":"Location request timed out. Try again or enter the landmark below.";setGeoStatus(message);},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
  async function saveDraft(){setDraftStatus("Saving draft…");try{const draft:ReportDraft={category,severity,note,photos:photos.map(photo=>photo?{id:photo.id,file:photo.file}:null),latitude,longitude,address};await writeDraft(draft);setDraftStatus(`Draft saved on this device · ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`);}catch{setDraftStatus("Could not save draft. Check browser storage space and try again.");}}
  async function submitReport(){if(uploadedCount<3)return;setSuccess(true);photos.forEach(photo=>{if(photo)URL.revokeObjectURL(photo.src);});setPhotos([null,null,null]);setCategory(categories[0]);setSeverity("Urgent / Obstruction");setNote("");setLatitude(null);setLongitude(null);setGeoStatus("Location not captured · use your device GPS");setAddress("");setPhotoError("");try{await deleteDraft();setDraftStatus("");}catch{setDraftStatus("Report submitted, but the saved local draft could not be removed from this browser.");}}
  function toPhoto(file:File):ReportPhoto{return {id:crypto.randomUUID(),file,src:URL.createObjectURL(file)};}
  function pickSlotPhoto(event:ChangeEvent<HTMLInputElement>,index:number){const file=event.currentTarget.files?.[0];event.currentTarget.value="";if(!file)return;if(!file.type.startsWith("image/")){setPhotoError("Only image files can be added as issue evidence.");return;}const photo=toPhoto(file);if(photos[index])URL.revokeObjectURL(photos[index]!.src);setPhotos(current=>{const next=[...current];next[index]=photo;return next;});setPhotoError("");setSuccess(false);}
  function pickPhotos(event:ChangeEvent<HTMLInputElement>){const selected=Array.from(event.currentTarget.files??[]);event.currentTarget.value="";const valid=selected.filter(file=>file.type.startsWith("image/"));if(valid.length!==selected.length)setPhotoError("Only image files can be added as issue evidence.");else setPhotoError("");if(!valid.length)return;const additions=valid.map(toPhoto);setPhotos(current=>{const next=[...current];for(const photo of additions){const openSlot=next.slice(0,3).findIndex(item=>item===null);const index=openSlot===-1?next.length:openSlot;next[index]=photo;}return next;});setSuccess(false);}
  function removePhoto(index:number){const photo=photos[index];if(photo)URL.revokeObjectURL(photo.src);setPhotos(current=>{if(index<3){const next=[...current];next[index]=null;return next;}return current.filter((_,photoIndex)=>photoIndex!==index);});setSuccess(false);}  return <div className={styles.page}><PortalHeader compact active="My Reports"/><main className={styles.main}>
    <div className={styles.breadcrumb}><Link href="/portal">⌂ Portal</Link><span>/</span><Link href="/portal">Citizen Action Console</Link><span>/</span><b>Report Issue</b><span className={styles.sla}>● Municipal Dispatch Ready · Central Zone SLA: <strong>≤ 6 Mins</strong></span></div>
    <section className={styles.title}><div><span className={styles.audit}>♧ SAAF GROUND AUDIT PROTOCOL 2.4</span><h1>Spot &amp; Report Civic Sanitation Issue</h1><p>Submit verified ground evidence to trigger high-priority municipal dispatch and notify accredited neighborhood clean-up taskforces.</p></div><div className={styles.ticket}><Icon>▣</Icon><span><small>ASSIGNED REFERENCE</small><b>ND-2025-W84-9042</b></span></div></section>
    <section className={styles.stepper}><div className={styles.step}><b>{uploadedCount>=3?"✓":"1"}</b><span><small>STEP 01</small><strong>Multi-Angle Capture</strong><small>{uploadedCount} of 3 angle slots filled</small></span></div><i/><div className={`${styles.step} ${styles.current}`}><b>2</b><span><small>STEP 02</small><strong>Geotag &amp; Ward</strong><small>{latitude!==null?"GPS captured":"GPS not captured"}</small></span></div><i/><div className={styles.step}><b>3</b><span><small>STEP 03</small><strong>Issue Details</strong><small>Category &amp; Access Notes</small></span></div><i/><div className={styles.step}><b>4</b><span><small>STEP 04</small><strong>AI Authenticity &amp; Dispatch</strong><small>Tamper Guard &amp; Confirmation</small></span></div></section>
    <div className={styles.columns}><div className={styles.left}>
      <section className={styles.panel}><div className={styles.panelHeading}><Icon>▣</Icon><div><b>Multi-Angle Photo Evidence</b><small>Upload a photo into each angle slot. Each selected image replaces its placeholder; add extra images after filling the first three.</small></div><label className={styles.upload}>＋ Add photos<input type="file" accept="image/*" multiple onChange={pickPhotos} aria-label="Upload three or more issue photos from different angles"/></label></div><div className={styles.angleGuidance}><b>{uploadedCount} of 3 angle slots filled</b><span className={uploadedCount>=3?styles.ready:""}>{uploadedCount>=3?"Minimum met":"Fill each photo slot to continue"}</span><div><small>01　Context</small><small>02　Materials</small><small>03　Detail</small></div></div>{photoError&&<p className={styles.photoError} role="alert">{photoError}</p>}<div className={styles.evidenceGrid}>{Array.from({length:Math.max(3,photos.length)},(_,i)=>{const photo=photos[i];const angle=["Context","Materials","Detail"][i]??`Angle ${i+1}`;return <article className={`${styles.uploadedPhoto} ${photo?styles.hasPhoto:styles.emptySlot}`} key={photo?.id??`empty-angle-${i}`}>
{photo?<><div className={styles.imageWrap}><img src={photo.src} alt={`Issue evidence, angle ${i+1}: ${photo.file.name}`}/><small>ANGLE {String(i+1).padStart(2,"0")} · {angle.toUpperCase()}</small><span>✓</span><label className={styles.replaceImage}>↻ Replace<input type="file" accept="image/*" onChange={event=>pickSlotPhoto(event,i)} aria-label={`Replace angle ${i+1} photo`}/></label></div><b title={photo.file.name}>{angle}</b><div className={styles.photoCardFooter}><small>{photo.file.name}</small><button type="button" onClick={()=>removePhoto(i)} aria-label={`Remove angle ${i+1} photo`}>Remove</button></div></>:<label className={styles.emptyPhoto}><span>＋</span><b>Upload photo</b><small>Angle {String(i+1).padStart(2,"0")} · {angle} view</small><input type="file" accept="image/*" onChange={event=>pickSlotPhoto(event,i)} aria-label={`Upload angle ${i+1}, ${angle} view`}/></label>}</article>})}</div><div className={styles.aiNote}>♧ AI Multiple perspectives alleviate the automated triage engine to measure debris depth and approximate tonnage before deployment.</div></section>
      <section className={styles.panel}><div className={styles.sectionHeading}><Icon>▤</Icon><b>Issue Classification &amp; Severity</b><small>Identify the primary sanitation violation to dispatch the appropriate municipal machinery (suction jetter, tipper, or compact compactor).</small></div><div className={styles.categories}>{categories.map((item,i)=><button type="button" key={item} onClick={()=>setCategory(item)} className={`${styles.category} ${category===item?styles.selected:""}`}><b>{["▧","⚒","⌂","△","♧","▣"][i]}　{item}</b><small>{["Organic bins, scattered solid municipal waste to sidewalk edge.","Bricks, rubble, abandoned plaster & construction debris.","Blocked drain culverts, monsoon overflow & silt stagnation.","Medical, clinical containers, hazardous materials.","Blackwater pipeline breach, septic backup & sewer seepage.","Unhygienic public toilet, broken facilities & fixtures."][i]}</small></button>)}</div><div className={styles.severity}><b>Severity &amp; Traffic Impact</b><span>Affects pedestrian walkway &amp; road shoulder</span><div>{["Routine Cleanup","Elevated Priority","Urgent / Obstruction","Hazardous Spill"].map(item=><button key={item} type="button" onClick={()=>setSeverity(item)} className={severity===item?styles.severityActive:""}>{item}</button>)}</div></div><label className={styles.noteLabel}>Ground Access Notes &amp; Specific Landmarks <small>{note.length}/500 characters</small><textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="The community bin at the junction has spilled over onto the pedestrian walkway and is blocking the stormwater gully. Mention any access constraints for the municipal tipper truck."/></label><small className={styles.hint}>ⓘ Specify exact landmarks (underpass, metro entry) to assist municipal crews.</small></section>
      <section className={styles.reporter}><span>AS</span><div><b>Aarav Sharma <small>Tier 2 · Civic Auditor</small></b><small>+91 98110-XXXXX · Ward 84 Registered Resident</small><p>Your credentials remain visible to verified Municipal Zone Officers &amp; NGO Dispatch for SLA compliance tracking while safeguarding your public anonymity.</p></div><label><input type="checkbox"/> Anonymous on Public Feed</label></section>
    </div><aside className={styles.right}>
      <section className={styles.aiCard}><header><Icon>✳</Icon><div><b>SAAF AI DEFENSE ENGINE</b><small>100% GENUINE</small></div></header><h2>Zero Tamper Verified</h2><p>Real-time deepfake &amp; duplicate detection passed via cryptographic verification protocol.</p>{[["Synthetic Image Classifier","0.03% AI Generation Likelihood (Safe)"],["Sensor Noise & Focal Depth","Hardware Bayes matrix matches Phone 14 Pro"],["Solar Azimuth Corroboration","Observed angle 31.2° aligns with sun position"],["Anti-Recycling Deduplication","Perceptual hash collision 0.14% in Ward 84"]].map(([t,d])=><div className={styles.check} key={t}><b>✓</b><span><strong>{t}</strong><small>{d}</small></span></div>)}<div className={styles.load}><span><small>ESTIMATED LOAD</small><b>1.8 – 2.4 Metric Tons</b></span><span><small>Response Mode</small><b>Requires Mini-Tipper</b></span></div></section>
      <section className={styles.location}><header><Icon>⌖</Icon><b>Geotag &amp; Ward</b><span>GPS LOCKED</span></header><div className={styles.miniMap}><span>●</span><small>{latitude!==null&&longitude!==null?`${latitude.toFixed(5)}° ${latitude>=0?"N":"S"}, ${Math.abs(longitude).toFixed(5)}° ${longitude>=0?"E":"W"}`:"Capture your current position"}</small></div><p className={styles.geoStatus} role="status">{geoStatus}</p><h3>DESIGNATED WARD JURISDICTION</h3><b>Ward 84 · Civil Lines &amp; Kashmere Gate</b><p>Central Delhi Municipal Zone · SLA Lead: Er. Rajesh Mathur</p><label>Street Address / Landmark<input value={address} onChange={event=>setAddress(event.target.value)}/></label><button type="button" className={styles.adjust} onClick={captureLocation}>⌖　{latitude===null?"Use my current location":"Refresh GPS location"}</button></section>
      <section className={styles.submitCard}><div className={styles.slaNote}>♧ <span><b>Guaranteed Response SLA</b><small>Accredited NGO taskforce or MCD sanitation tipper assigned within 95 minutes of digital signature verification.</small></span></div><small className={styles.uploadRequirement}>{uploadedCount<3?"Fill all 3 angle slots before submitting.":"Photo requirement met · "+uploadedCount+" images ready"}</small><button type="button" className={styles.submit} disabled={uploadedCount<3} onClick={submitReport}>{success?"✓ Report Submitted · #MCD-8409":"Submit Verified Report　➤"}</button>{!success&&<><button type="button" className={styles.draft} onClick={saveDraft} disabled={!restored}>♙　Save Draft on this device</button>{draftStatus&&<small className={styles.draftStatus} role="status">{draftStatus}</small>}</>}<small>★ Critical Spill or Acute danger? Hotline: <a href="tel:18002447233">1800-244-SAAF</a></small></section>
    </aside></div>
    <section className={styles.transparency}><div>◉ <span><b>Real-Time Open Data Transparency</b><small>Once submitted, this report’s pipeline timeline will be transparent to citizens via satellite &amp; geotag audits.</small></span></div><b>94.8%<small>Ward 84 SLA Cleared</small></b><b>32m<small>Avg Heat Dispatch</small></b></section>
  </main><PortalFooter compact/></div>;
}
