import Link from "next/link";
import { PublicSiteFooter, PublicSiteHeader } from "./PublicSiteShell";
import styles from "./RoleEntryPage.module.css";

const portals=[
 {icon:"▣",tier:"Public Tier",tone:"citizen",title:"Citizen",description:"Empowering residents across 12 zones with instant verification tools and verified civic action tickets.",features:["Geotagged Multi-Angle Incident Capture","AI Authenticity & Anti-Spoof Verification","Community Follow-up Confirmation Gate","Safai Corps Weekend Volunteer Roster"],label:"Continue as Citizen",href:"/portal"},
 {icon:"♟",tier:"Field Execution",tone:"ngo",title:"NGO Partner",description:"Verified ground organizations leading ward sweep operations, crew mobilization, and tangible cleanup tasks.",features:["Ward-Based Mission Queue (Accept/Decline)","Volunteer Mobilization & Roster Management","Dual-Angle Evidence Capture (Before/After)","Expense Logging & CSR Milestone Claims"],label:"Enter NGO Console",href:"/ngo"},
 {icon:"▤",tier:"Impact Funding",tone:"csr",title:"CSR & ESG Partner",description:"Corporate philanthropies funding zero-waste projects, tracking live deployments, and downloading statutory ESG proofs.",features:["Direct Mission Escrow Funding","Real-Time Field Crew Telemetry & OPEX","Automated NGO Matchmaking & Unassigned Queue","SEBI & MCA Rule 2014 ESG Compliance"],label:"Access CSR Portal",href:"/csr"},
 {icon:"▦",tier:"Command Tier",tone:"admin",title:"Admin",description:"SAAF software management team.",features:["Ward Sanitation Telemetry across Delhi NCT","Cryptographic Photo Audit Validation","Algorithmic Chronic Recurrence Engine","CSR Fund Flow & Commissioner Escalation"],label:"Open Admin Command",href:"/admin"},
];

export default function RoleEntryPage(){return <div className={styles.page}><PublicSiteHeader/><main className={styles.main}><div className={styles.utilityLine}><span className={styles.security}>● RBAC Security Level 4</span><i/> <b>NCT CIVIC OPERATING GRID</b><span>♙ DigiLocker &amp; Parichay Ready</span><strong>Active Nodes: 272 Wards</strong></div><header className={styles.heading}><span className={styles.framework}>♧ Delhi NCT Urban Sanitation Modernization Framework</span><h1>Select Your Operational Role</h1><p>Choose your accredited tier to access specialized workspaces, ward-level telemetry, field dispatch pipelines, or cryptographically verified SLA ledgers across the National Capital Territory.</p></header><div className={styles.selectorLabel}>PRIMARY PORTAL SELECTOR (QUICK SWITCH)</div><details className={styles.selector}><summary><span className={styles.selectIcon}>♙</span><span><b>Select your operating credential…</b><small>Citizen　•　NGO　•　CSR Sponsor　•　Municipal Authority</small></span><small>Press 1–4　⌄</small></summary><div><Link href="/portal">1　 Citizen Portal →</Link><Link href="/ngo">2　 NGO Partner Console →</Link><Link href="/csr">3　 CSR &amp; ESG Portal →</Link><Link href="/admin">4　 Municipal Command →</Link></div></details>
  <section className={styles.cards}>{portals.map(portal=><article className={styles.card} key={portal.title}><div className={styles.cardTop}><span className={`${styles.cardIcon} ${styles[portal.tone]}`}>{portal.icon}</span><span className={`${styles.tier} ${styles[`tier_${portal.tone}`]}`}>{portal.tier}</span></div><h2>{portal.title}</h2><p>{portal.description}</p><ul>{portal.features.map(feature=><li key={feature}>{portal.tone==="csr"?"▣":"✓"}　{feature}</li>)}</ul><Link className={styles.continue} href={portal.href}>{portal.label}<b>→</b></Link></article>)}</section>
  <section className={styles.health}><header><div><small>DELHI NCT NETWORK HEALTH</small><h2>Real-Time Grid Status Across 12 Administrative Zones</h2></div><span>● Telemetry Active · Latency 240ms</span></header><div className={styles.healthStats}>{[["ACTIVE WARDS","272 / 272","✓ 100% On-grid"],["24H RESOLVED SLA","94.8%","↗ +3.2% vs last week"],["ACTIVE NGO CREWS","142","♟ 1,890 sanitarians"],["CSR ESCROW ALLOCATED","₹4.82 Cr","▣ 38 Active missions"]].map(([label,value,detail])=><article key={label}><small>{label}</small><b>{value}</b><span>{detail}</span></article>)}</div></section>
  <section className={styles.verify}><span className={styles.question}>?</span><div><b>Need Institutional Role Accreditation?</b><small>NGOs and Corporate CSR departments must complete one-time verification via MCD Darpan or MCA CIN registry.</small></div><button disabled>Verify DigiLocker</button><button className={styles.request} disabled>Request Accreditation</button></section>
 </main><PublicSiteFooter/></div>}
