"use client";
import { useState } from "react";
import Link from "next/link";
import { Eyebrow, Icon, PortalFooter } from "./PortalShell";
import styles from "./VolunteerPage.module.css";

const missions=[
 {id:"yamuna",image:"mission-yamuna.png",tag:"URGENT WEEKEND DRIVE",ward:"Ward 84 · 1.2 km away",name:"Yamuna Ghat Plastic Interception & Storm Drain Desilting",desc:"Riverbank sorting, floating plastic boom deployment, heavy silt extraction from overfull outfalls, and temporary safety cordoning.",when:"Sat, 22 Feb · 07:30 AM – 11:30 AM",place:"Red Zone · Safai Shakti Guild (Rajesh Pawar)",team:"14 of 20 Volunteers Mobilized",left:"6 Spots Remaining",gear:["High-Vis Vest","Nitrile Gloves","N95 Mask","Hydration Pack"]},
 {id:"kashmere",image:"mission-kashmere.png",tag:"WEEKEND SCHEDULED",ward:"Ward 84 · 650m away",name:"Kashmere Gate ISBT Commercial Rubble & Flyover Cleanout",desc:"Segregation of commercial packaging debris, machine-assisted brown cleaning, manual heavy rubble loading onto municipal tipper trucks.",when:"Sun, 23 Feb · 08:00 AM – 11:00 AM",place:"Lead NGO · CleanCity Alliance",team:"12 of 20 Volunteers Filled",left:"8 Spots Remaining",gear:["Fluorescent Safety Batons","Reinforced Kevlar Gloves","Hydration Pack"]},
 {id:"mori",image:"mission-mori-gate.png",tag:"ECO-PLANTING & SCREENING",ward:"Ward 42 · 2.4 km away",name:"Mori Gate Sluice Debris Screening & Median Planting",desc:"Bio-waste screening along the open stormwater gutters followed by municipal green belt replanting with native pollution-filtering saplings.",when:"Next Wed, 26 Feb · 04:30 PM – 07:00 PM",place:"Lead NGO · New Karma Eco Taskforce",team:"10 of 25 Volunteers Filled",left:"15 Spots Remaining",gear:["Planting Tools","Cotton Garden Gloves","Botanical Manual"]},
];

export default function VolunteerPage(){const [selected,setSelected]=useState("yamuna");const [time,setTime]=useState("Morning Shift");const [confirmed,setConfirmed]=useState(false);return <div className={styles.page}>
  <header className={styles.topbar}><Link href="/portal" className={styles.brand}><span>✳</span><b>SAAF</b><small>CIVIC CLEANLINESS</small></Link><nav><Link href="/portal">Hub Overview</Link><Link href="/report">Report Issue</Link><Link href="/portal">My Reports</Link><Link href="/">Neighborhood Activity</Link></nav><a href="tel:18002447233" className={styles.hotline}>☎ EMERGENCY HOTLINE<br/><b>1800-244-SAAF</b></a><span className={styles.user}>Aarav Sharma<br/><small>Ward 84 · Civil Lines</small></span><Link href="/portal" className={styles.profile}>A</Link><details className={styles.menu}><summary>☰</summary><nav><Link href="/portal">Hub Overview</Link><Link href="/report">Report Issue</Link><Link href="/volunteer">Volunteer Missions</Link></nav></details></header>
  <main><div className={styles.breadcrumb}><Link href="/portal">⌂ Portal</Link>　/　Citizen Action Console　/　<b>Volunteer Missions</b></div>
    <section className={styles.hero}><div><span className={styles.missionTag}>♧ MCD ACCREDITED COMMUNITY MISSION</span><h1>Join Verified Civic Action Taskforces in Ward 84</h1><p>Lend a hand in neighborhood desilting, segregation, and cleanups led by accredited municipal NGOs.<br/>Earn recognized civic credits, verifiable attendance records, and complete safety equipment.</p></div><div className={styles.medical}><Icon>✚</Icon><span><small>MEDICAL &amp; SLA BACKUP</small><b>On-Site Paramedic Unit</b></span></div></section>
    <section className={styles.stats}>{[["♙","3","Ward 84 Missions (Within 3km)"],["♧","342","Volunteers Mobilized this Month"],["⛨","100% Free","Safety PPE & N95 Masks Supplied"],["♙","MCD Certified","Digital Karma Credit Protocol"]].map(([icon,value,label])=><article key={label}><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></article>)}</section>
    <div className={styles.content}><section className={styles.missionSection}><div className={styles.sectionTitle}><div><h2>Local Missions Around You</h2><p>Select an active neighborhood drive to prefill task targets &amp; shift roster.</p></div><button type="button" className={styles.filter}>◌ Live Geospatial Filter</button></div><div className={styles.missions}>{missions.map((mission)=><article className={`${styles.mission} ${selected===mission.id?styles.chosen:""}`} key={mission.id} onClick={()=>setSelected(mission.id)}><div className={styles.missionHeading}><b className={mission.id==="yamuna"?styles.urgent:mission.id==="mori"?styles.eco:styles.scheduled}>{mission.tag}</b><small>{mission.ward}</small>{selected===mission.id&&<span>✓ Selected</span>}</div><h3>{mission.name}</h3><p>{mission.desc}</p><div className={styles.missionInfo}><img src={`/citizen/${mission.image}`} alt=""/><div><span>◷　{mission.when}</span><span>♧　{mission.place}</span><small>{mission.team}</small><div className={styles.progress}><i style={{width:mission.id==="yamuna"?"70%":mission.id==="kashmere"?"60%":"40%"}}/></div></div><b>{mission.left}</b></div><div className={styles.gear}>{mission.gear.map(item=><span key={item}>{item}</span>)}</div></article>)}</div><button className={styles.mapButton}>⌖　 Explore Interactive Ward 84 Taskforce Map <span>⇱ Open GIS Map</span></button></section>
    <aside className={styles.form}><div className={styles.formTitle}><Icon>♙</Icon><div><Eyebrow>CIVIC ENROLMENT</Eyebrow><h2>Volunteer Sign-up Form</h2></div><small>Single-Step Enrollment</small></div><div className={styles.missionSelected}>▣　 MISSION TARGET<small>{missions.find(m=>m.id===selected)?.name}</small></div><div className={styles.fields}><label>Full Name<input defaultValue="Aarav Sharma"/></label><label>Date of Birth<input type="date" defaultValue="1998-08-14"/></label><label>Email Address<input type="email" defaultValue="aarav.sharma@civicmail.in"/></label><label>Phone Number<div className={styles.phone}>+91 <input defaultValue="98112-40912"/><b>✓ DigiLocker Verified</b></div></label></div><div className={styles.otp}>▣　 OTP Active</div><fieldset><legend>What kind of work would you like to do?</legend><small>Select roles you are comfortable supporting:</small><div className={styles.roles}>{["Waste Segregation & Plastic Triage","Drain Desilting & Ground Support","Community Marshalling & Safety Cordons","Photo Telemetry & Verification Audit","PPE Logistics & Hydration Station"].map((role,i)=><label key={role}><input type="checkbox" defaultChecked={i===0||i===2}/><span><b>{role}</b><small>{["Sorting recyclables & facilitating triage","Assisting mechanized & manual clearance crews","Guiding pedestrians & maintaining heavy machinery zones","Progress logging & evidence upload","Managing gloves, drinking water, and first aid"][i]}</small></span></label>)}</div></fieldset><fieldset><legend>Select Preferred Shift Window</legend><div className={styles.shifts}>{["Morning Shift","Evening Shift","Weekend Blitz","Rapid Standby"].map((item,i)=><label key={item}><input type="radio" name="shift" checked={time===item} onChange={()=>setTime(item)}/><span><b>{item}</b><small>{["07:00 AM – 10:30 AM (Morning focus)","04:30 PM – 07:00 PM (Adult focus)","Saturday & Sunday Rollout","On-call for emergency notices"][i]}</small></span></label>)}</div></fieldset><label className={styles.emergency}>Emergency Contact &amp; Health Note (Optional)<input placeholder="e.g. Asthmatic (outdoor dust sensitive) / Contact: 98110-XXXXX"/></label><label className={styles.consent}><input type="checkbox"/><span>I agree to adhere to MCD sanitation safety protocols, strictly wear high-visibility PPE &amp; nitrile gloves provided on-site, and follow instructions from the designated NGO Mission Commander.</span></label><button className={styles.submit} onClick={()=>setConfirmed(true)}>{confirmed?"✓ Registration Confirmed":"Confirm Volunteer Registration　♙"}</button><button className={styles.back} onClick={()=>setConfirmed(false)}>↶　Join General Ward 84 Volunteer Pool</button><div className={styles.info}>▣　You will instantly receive an automated WhatsApp confirmation with reporting coordinates, WhatsApp group link, and digital credentials to redeem your sanitized safety kit.</div></aside></div>
    <section className={styles.safety}><div className={styles.sectionTitle}><div><Eyebrow>PUBLIC ACCOUNTABILITY</Eyebrow><h2>Why Volunteer with SAAF?</h2></div><small>⛨ Civic Safety Warranty Standard v2.0</small></div><div>{[["♧","Accredited NGOs Only","Every clean-up taskforce lead is pre-vetted and audited by the Municipal Corporation of Delhi (MCD)."],["⛨","Insurance & First Aid","Active civic volunteers are covered by standard municipal incident coverage and immediate on-ground medical backup."],["♙","Digital Karma & Credits","Receive verifiable blockchain-hashed digital volunteer certificates eligible for college civic credits and corporate CSR awards."],["✳","CSR Matched Impact","Every kilo of plastic segregated unlocks matching municipal CSR funding for advanced mechanization."]].map(([icon,title,desc])=><article key={title}><Icon>{icon}</Icon><b>{title}</b><p>{desc}</p></article>)}</div></section>
  </main><PortalFooter compact/></div>}
